# docker composerのバージョンの指定
version: "3.9"

services:
  node:
    # buildするdockerfileの位置
    build: ./front
    # 作成するdockerコンテナの名前
    container_name: node
    # docker内と共有するフォルダの指定
    volumes:
      - ./front/React:/front
      # - ./front/scripts:/front
    # docker内に入った時の初期パスの指定
    working_dir: /front
    # コンテナにバインドするポートの指定（左:自分のPCポート、右:dookerコンテナのポート）
    ports:
      - 3000:3000
    # コンテナが勝手に終了しないための設定
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
    # ホットリロードを行う設定
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - front_network

  flask:
    container_name: flask
    depends_on:
      - db
    build: ./backend/flask_app
    ports:
      - "5001:5000"
    volumes:
      - ./backend/flask_app/app:/usr/src/app:cached
      # - ./backend/DB:/usr/src/db:cached
      - ./backend/flask_app/scripts:/usr/src/scripts:cached
    working_dir: /usr/src/scripts
    command: bash -c "./run.sh"
    networks:
      - backend_network
    environment:
      # APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev
      
  db:
    container_name: mysql_db
    build: ./backend/DB
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./backend/DB/docker-entrypoint:/docker-entrypoint-initdb.d
      - ./log/db:/var/log/mysql:cached
    networks:
      - backend_network
    environment:
      # APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.dev
    links:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - backend_network

  web:
    

networks:
  # default:
  #   external:
  #     name: bridge
  backend_network:
    name: backend_network
    driver: bridge
    # external: true
  front_network:
    name: front_network
    driver: bridge
    # external: true