# docker composerのバージョンの指定
version: "3.9"

services:
  front:
    # 作成するdockerコンテナの名前
    container_name: front
    build:
      context: .
      # buildするdockerfileの位置
      # 本番用
      dockerfile: ./front/Dockerfile.prod
    # docker内に入った時の初期パスの指定
    working_dir: /app
    # docker内と共有するフォルダの指定
    volumes:
      - ./front/React:/app
      - ./gunicorn_socket:/tmp/gunicorn_socket
      # - ./front/React/src:/app/src
      - ssl:/etc/letsencrypt
    # コンテナにバインドするポートの指定（左:自分のPCポート、右:dookerコンテナのポート）
    ports:
      - "80:80"
    # コンテナが勝手に終了しないための設定
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定
    stdin_open: true
    # ホットリロードを行う設定
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - my_network

  flask:
    container_name: flask
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/flask_app/Dockerfile
    ports:
      - 5001:5001
    expose:
      - "5001"
    volumes:
      - ./backend/flask_app/app:/var/www/
      - ./backend/flask_app/scripts:/var/www/scripts
      - ./gunicorn_socket:/tmp/gunicorn_socket
    working_dir: /var/www/scripts
    command: bash -c "./run.sh"
    networks:
      - my_network
    environment:
      # APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev
      
  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: ./backend/DB/Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./backend/DB/docker-entrypoint:/docker-entrypoint-initdb.d
      - ./log/db:/var/log/mysql:cached
    networks:
      - my_network
    environment:
      # APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.dev
    links:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - my_network

volumes:
  socket:
  ssl:

networks:
  # default:
  #   external:
  #     name: bridge
  my_network:
    name: my_network
    driver: bridge
    # external: true