POST http://localhost:5000/result HTTP/1.1
content-type: application/json

{
    "result_id": 10,
    "user_id": 10,
    "accuracy_value": 10,
    "wpm": 10,
     "playd_at_date": "2022-07-10"
 }

###
GET http://localhost:5000/result HTTP/1.1
###
GET http://localhost:5000/result/user HTTP/1.1

###
GET http://localhost:5000/result/1 HTTP/1.1
###
GET http://localhost:5000/result/2 HTTP/1.1



###
POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "user_name": "にし",
    "password": "1"
}
###
POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "user_name" : "山田長政",
    "password" : "test1"
}
###
POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "user_name" : "浅井長政",
    "password" : "test2"
}
###
POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "user_name" : "滝廉太郎",
    "password" : "test3"
}




###
GET http://localhost:5000/user HTTP/1.1

###
POST http://localhost:5000/user/login HTTP/1.1
content-type: application/json

{
    "user_name": "山田長政",
    "password": "test1"
}

