POST http://localhost:5000/result HTTP/1.1
content-type: application/json

{
    "result_id": 111111,
    "user_id": 333333,
    "accuracy_value": 555555,
    "wpm": 7777777,
     "playd_at_date": "2022-06-13"
 }

###
POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "id": 333333,
    "user_name": "school",
    "password": "ProtoOu"
}

###
GET http://localhost:5000/user HTTP/1.1


