"""db start

Revision ID: c2ef95d563ed
Revises: 
Create Date: 2022-06-26 15:09:35.729151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ef95d563ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('terminologies',
    sa.Column('terminologie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('theme_jp', sa.String(length=255), nullable=True),
    sa.Column('theme_ro', sa.String(length=255), nullable=True),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('description_ro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('terminologie_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accuracy_value', sa.Float(), nullable=True),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('playd_at_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('users')
    op.drop_table('terminologies')
    op.drop_table('genres')
    # ### end Alembic commands ###
