# build用の設定
# dockerHubから持ってくるImageの指定
FROM node:16.15.0-alpine3.15 AS builder

# 使用するnodeのバージョンの指定
ENV NODE_VERSION 16.15.0
# docker内に入った時の初期パスの指定
WORKDIR /app
# ローカル側のファイルをdocker内にコピーする
COPY ./front/React /app
# コンテナが勝手に終了してしまわないようにする設定
ENV CI=true

CMD npm install && npm run build