FROM nginx:latest

# RUN rm -rf /etc/nginx/conf.d/default.conf

COPY ./web/default.conf /etc/nginx/conf.d/default.conf
# COPY ./web/nginx.conf /etc/nginx/conf.d/nginx.conf
# CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/conf.d/nginx.conf"]